# Example YAML file for use in LBL

# Set instrument name
INSTRUMENT: SPIROU

# Set data directory
DATA_DIR: /data/spirou/data/lbl

# Set science object name
OBJECT_SCIENCE: GL699

# Set template object name
OBJECT_TEMPLATE: GL699

# Set the science input file string
INPUT_FILE: '*e2dsff*AB.fits'

# Set blaze file (None for default)
BLAZE_FILE: 2498F798T802f_pp_blaze_AB.fits

# Set template file (None for default)
TEMPLATE_FILE: None

# Set whether to plot any plots
PLOT: True

# Set whether to do the compute ccf plot
PLOT_COMPUTE_CCF: False

# Set whether to do the compute line plot
PLOT_COMPUTE_LINES: False

# set whether to do the compil cumulative plot
PLOT_COMPIL_CUMUL: True

# Define whether to do the compil binned plot
PLOT_COMPIL_BINNED: True

# Define whether to skip done files
SKIP_DONE: False