# Example YAML file for use in LBL

# Set instrument name
INSTRUMENT: SPIROU

# Set data directory
DATA_DIR: /data/spirou/data/lbl

# Set science object name
OBJECT_SCIENCE: GL699

# Set template object name
OBJECT_TEMPLATE: GL699

# Set the science input file string
INPUT_FILE: '*e2dsff*AB.fits'

# Set whether to plot
PLOT: True

# Set whether to debug plot
DEBUG_PLOT: True

# Set blaze file (None for default)
BLAZE_FILE: None

# Set template file (None for default)
TEMPLATE_FILE: None